//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace LbcConsultaUsuarioSistema {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaUsuarioSistemaSoap", Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuarioSistema : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarUsuarioSistemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarUsuariosArgosPorRolIdSistemaOperationCompleted;
        
        /// <remarks/>
        public ConsultaUsuarioSistema() {
            this.Url = "http://desarrollo.lbc.bo/Servicios/generales/ConsultaUsuarioSistema.asmx";
        }
        
        /// <remarks/>
        public event ConsultarUsuarioSistemaCompletedEventHandler ConsultarUsuarioSistemaCompleted;
        
        /// <remarks/>
        public event ConsultarUsuariosArgosPorRolIdSistemaCompletedEventHandler ConsultarUsuariosArgosPorRolIdSistemaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarUsuarioSistema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioSistemaEntity ConsultarUsuarioSistema(string usuario, string sistema, string password) {
            object[] results = this.Invoke("ConsultarUsuarioSistema", new object[] {
                        usuario,
                        sistema,
                        password});
            return ((UsuarioSistemaEntity)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsultarUsuarioSistema(string usuario, string sistema, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsultarUsuarioSistema", new object[] {
                        usuario,
                        sistema,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public UsuarioSistemaEntity EndConsultarUsuarioSistema(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UsuarioSistemaEntity)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarUsuarioSistemaAsync(string usuario, string sistema, string password) {
            this.ConsultarUsuarioSistemaAsync(usuario, sistema, password, null);
        }
        
        /// <remarks/>
        public void ConsultarUsuarioSistemaAsync(string usuario, string sistema, string password, object userState) {
            if ((this.ConsultarUsuarioSistemaOperationCompleted == null)) {
                this.ConsultarUsuarioSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarUsuarioSistemaOperationCompleted);
            }
            this.InvokeAsync("ConsultarUsuarioSistema", new object[] {
                        usuario,
                        sistema,
                        password}, this.ConsultarUsuarioSistemaOperationCompleted, userState);
        }
        
        private void OnConsultarUsuarioSistemaOperationCompleted(object arg) {
            if ((this.ConsultarUsuarioSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarUsuarioSistemaCompleted(this, new ConsultarUsuarioSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarUsuariosArgosPorRolIdSistema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuariosSistemaEntity ConsultarUsuariosArgosPorRolIdSistema(string rol, string sistema) {
            object[] results = this.Invoke("ConsultarUsuariosArgosPorRolIdSistema", new object[] {
                        rol,
                        sistema});
            return ((UsuariosSistemaEntity)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsultarUsuariosArgosPorRolIdSistema(string rol, string sistema, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsultarUsuariosArgosPorRolIdSistema", new object[] {
                        rol,
                        sistema}, callback, asyncState);
        }
        
        /// <remarks/>
        public UsuariosSistemaEntity EndConsultarUsuariosArgosPorRolIdSistema(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UsuariosSistemaEntity)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarUsuariosArgosPorRolIdSistemaAsync(string rol, string sistema) {
            this.ConsultarUsuariosArgosPorRolIdSistemaAsync(rol, sistema, null);
        }
        
        /// <remarks/>
        public void ConsultarUsuariosArgosPorRolIdSistemaAsync(string rol, string sistema, object userState) {
            if ((this.ConsultarUsuariosArgosPorRolIdSistemaOperationCompleted == null)) {
                this.ConsultarUsuariosArgosPorRolIdSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarUsuariosArgosPorRolIdSistemaOperationCompleted);
            }
            this.InvokeAsync("ConsultarUsuariosArgosPorRolIdSistema", new object[] {
                        rol,
                        sistema}, this.ConsultarUsuariosArgosPorRolIdSistemaOperationCompleted, userState);
        }
        
        private void OnConsultarUsuariosArgosPorRolIdSistemaOperationCompleted(object arg) {
            if ((this.ConsultarUsuariosArgosPorRolIdSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarUsuariosArgosPorRolIdSistemaCompleted(this, new ConsultarUsuariosArgosPorRolIdSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioSistemaEntity {
        
        private int codigoEstadoField;
        
        private EstadoUsuarioAd estadoField;
        
        private string usuarioField;
        
        private string nombreLargoField;
        
        private string nombresField;
        
        private string apellidosField;
        
        private string correoField;
        
        private string codigoSucursalField;
        
        private string sucursalField;
        
        private Rol[] rolesField;
        
        /// <remarks/>
        public int CodigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public EstadoUsuarioAd Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string NombreLargo {
            get {
                return this.nombreLargoField;
            }
            set {
                this.nombreLargoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
            }
        }
        
        /// <remarks/>
        public Rol[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EstadoUsuarioAd {
        
        /// <remarks/>
        NoEncontrado,
        
        /// <remarks/>
        Encontrado,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rol {
        
        private string codigoRolField;
        
        private string descripcionField;
        
        private int codigoSistemaField;
        
        private string descripcionSistemaField;
        
        private string estadoField;
        
        /// <remarks/>
        public string CodigoRol {
            get {
                return this.codigoRolField;
            }
            set {
                this.codigoRolField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionSistema {
            get {
                return this.descripcionSistemaField;
            }
            set {
                this.descripcionSistemaField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuariosSistemaEntity {
        
        private int codigoEstadoField;
        
        private EstadoUsuarioAd estadoField;
        
        private UsuarioSistemaEntity[] listaUsuarioSistemaField;
        
        /// <remarks/>
        public int CodigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public EstadoUsuarioAd Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public UsuarioSistemaEntity[] ListaUsuarioSistema {
            get {
                return this.listaUsuarioSistemaField;
            }
            set {
                this.listaUsuarioSistemaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ConsultarUsuarioSistemaCompletedEventHandler(object sender, ConsultarUsuarioSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarUsuarioSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarUsuarioSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioSistemaEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioSistemaEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ConsultarUsuariosArgosPorRolIdSistemaCompletedEventHandler(object sender, ConsultarUsuariosArgosPorRolIdSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarUsuariosArgosPorRolIdSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarUsuariosArgosPorRolIdSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuariosSistemaEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuariosSistemaEntity)(this.results[0]));
            }
        }
    }
}
