//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace LbcOnBaseWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OnBaseWSSoap", Namespace="http://tempuri.org/")]
    public partial class OnBaseWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerInformacionSolicitudOnBaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportarDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AvanzarProcesoOperationCompleted;
        
        /// <remarks/>
        public OnBaseWS() {
            this.Url = "http://desanilus.lbc.bo/Nilus/WsOnbase/OnBaseWS.asmx";
        }
        
        /// <remarks/>
        public event ObtenerInformacionSolicitudOnBaseCompletedEventHandler ObtenerInformacionSolicitudOnBaseCompleted;
        
        /// <remarks/>
        public event ImportarDocumentoCompletedEventHandler ImportarDocumentoCompleted;
        
        /// <remarks/>
        public event AvanzarProcesoCompletedEventHandler AvanzarProcesoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerInformacionSolicitudOnBase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoEntity ObtenerInformacionSolicitudOnBase(string NumeroSolicitud, SistemaOrigen SistemaOrigen) {
            object[] results = this.Invoke("ObtenerInformacionSolicitudOnBase", new object[] {
                        NumeroSolicitud,
                        SistemaOrigen});
            return ((ResultadoEntity)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerInformacionSolicitudOnBase(string NumeroSolicitud, SistemaOrigen SistemaOrigen, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerInformacionSolicitudOnBase", new object[] {
                        NumeroSolicitud,
                        SistemaOrigen}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResultadoEntity EndObtenerInformacionSolicitudOnBase(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResultadoEntity)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerInformacionSolicitudOnBaseAsync(string NumeroSolicitud, SistemaOrigen SistemaOrigen) {
            this.ObtenerInformacionSolicitudOnBaseAsync(NumeroSolicitud, SistemaOrigen, null);
        }
        
        /// <remarks/>
        public void ObtenerInformacionSolicitudOnBaseAsync(string NumeroSolicitud, SistemaOrigen SistemaOrigen, object userState) {
            if ((this.ObtenerInformacionSolicitudOnBaseOperationCompleted == null)) {
                this.ObtenerInformacionSolicitudOnBaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerInformacionSolicitudOnBaseOperationCompleted);
            }
            this.InvokeAsync("ObtenerInformacionSolicitudOnBase", new object[] {
                        NumeroSolicitud,
                        SistemaOrigen}, this.ObtenerInformacionSolicitudOnBaseOperationCompleted, userState);
        }
        
        private void OnObtenerInformacionSolicitudOnBaseOperationCompleted(object arg) {
            if ((this.ObtenerInformacionSolicitudOnBaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerInformacionSolicitudOnBaseCompleted(this, new ObtenerInformacionSolicitudOnBaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportarDocumento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoEntity ImportarDocumento(DocumentoOnBaseEntity documento, string[] archivosBase64, SistemaOrigen SistemaOrigen) {
            object[] results = this.Invoke("ImportarDocumento", new object[] {
                        documento,
                        archivosBase64,
                        SistemaOrigen});
            return ((ResultadoEntity)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportarDocumento(DocumentoOnBaseEntity documento, string[] archivosBase64, SistemaOrigen SistemaOrigen, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportarDocumento", new object[] {
                        documento,
                        archivosBase64,
                        SistemaOrigen}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResultadoEntity EndImportarDocumento(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResultadoEntity)(results[0]));
        }
        
        /// <remarks/>
        public void ImportarDocumentoAsync(DocumentoOnBaseEntity documento, string[] archivosBase64, SistemaOrigen SistemaOrigen) {
            this.ImportarDocumentoAsync(documento, archivosBase64, SistemaOrigen, null);
        }
        
        /// <remarks/>
        public void ImportarDocumentoAsync(DocumentoOnBaseEntity documento, string[] archivosBase64, SistemaOrigen SistemaOrigen, object userState) {
            if ((this.ImportarDocumentoOperationCompleted == null)) {
                this.ImportarDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportarDocumentoOperationCompleted);
            }
            this.InvokeAsync("ImportarDocumento", new object[] {
                        documento,
                        archivosBase64,
                        SistemaOrigen}, this.ImportarDocumentoOperationCompleted, userState);
        }
        
        private void OnImportarDocumentoOperationCompleted(object arg) {
            if ((this.ImportarDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportarDocumentoCompleted(this, new ImportarDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AvanzarProceso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultadoEntity AvanzarProceso(string NumeroSolicitud, string origen, string destino, SistemaOrigen SistemaOrigen) {
            object[] results = this.Invoke("AvanzarProceso", new object[] {
                        NumeroSolicitud,
                        origen,
                        destino,
                        SistemaOrigen});
            return ((ResultadoEntity)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAvanzarProceso(string NumeroSolicitud, string origen, string destino, SistemaOrigen SistemaOrigen, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AvanzarProceso", new object[] {
                        NumeroSolicitud,
                        origen,
                        destino,
                        SistemaOrigen}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResultadoEntity EndAvanzarProceso(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResultadoEntity)(results[0]));
        }
        
        /// <remarks/>
        public void AvanzarProcesoAsync(string NumeroSolicitud, string origen, string destino, SistemaOrigen SistemaOrigen) {
            this.AvanzarProcesoAsync(NumeroSolicitud, origen, destino, SistemaOrigen, null);
        }
        
        /// <remarks/>
        public void AvanzarProcesoAsync(string NumeroSolicitud, string origen, string destino, SistemaOrigen SistemaOrigen, object userState) {
            if ((this.AvanzarProcesoOperationCompleted == null)) {
                this.AvanzarProcesoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAvanzarProcesoOperationCompleted);
            }
            this.InvokeAsync("AvanzarProceso", new object[] {
                        NumeroSolicitud,
                        origen,
                        destino,
                        SistemaOrigen}, this.AvanzarProcesoOperationCompleted, userState);
        }
        
        private void OnAvanzarProcesoOperationCompleted(object arg) {
            if ((this.AvanzarProcesoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AvanzarProcesoCompleted(this, new AvanzarProcesoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SistemaOrigen {
        
        /// <remarks/>
        Concesionarias,
        
        /// <remarks/>
        Desgravamen,
        
        /// <remarks/>
        Siscar,
        
        /// <remarks/>
        Multifamiliar,
        
        /// <remarks/>
        Gcp,
        
        /// <remarks/>
        WSGcp,
        
        /// <remarks/>
        Cumulos,
        
        /// <remarks/>
        ListaAntiLavado,
        
        /// <remarks/>
        BdWholesale,
        
        /// <remarks/>
        PaginaWeb,
        
        /// <remarks/>
        Horus,
        
        /// <remarks/>
        Bse,
        
        /// <remarks/>
        Bga,
        
        /// <remarks/>
        AdmPagosSiniestros,
        
        /// <remarks/>
        CartasVencimiento,
        
        /// <remarks/>
        Helios,
        
        /// <remarks/>
        DebitoAutomatico,
        
        /// <remarks/>
        CobranzaMovil,
        
        /// <remarks/>
        WholesaleSiscar,
        
        /// <remarks/>
        BnbLeasing,
        
        /// <remarks/>
        Sintesis,
        
        /// <remarks/>
        TarificadorEF,
        
        /// <remarks/>
        OnBase,
        
        /// <remarks/>
        WinService,
        
        /// <remarks/>
        BancoGanadero,
        
        /// <remarks/>
        BancoGanaderoMasivo,
        
        /// <remarks/>
        CarreraAgentes,
        
        /// <remarks/>
        ICRL,
        
        /// <remarks/>
        MicrosegurosBancoSol,
        
        /// <remarks/>
        PagoFranquicias,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoEntity {
        
        private bool esValidoField;
        
        private string mensajeField;
        
        private object datosAdicionalesField;
        
        private MensajeEntity[] listaMensajesField;
        
        /// <remarks/>
        public bool EsValido {
            get {
                return this.esValidoField;
            }
            set {
                this.esValidoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public object DatosAdicionales {
            get {
                return this.datosAdicionalesField;
            }
            set {
                this.datosAdicionalesField = value;
            }
        }
        
        /// <remarks/>
        public MensajeEntity[] ListaMensajes {
            get {
                return this.listaMensajesField;
            }
            set {
                this.listaMensajesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeywordOnBaseEntity {
        
        private long idKeywordField;
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        public long idKeyword {
            get {
                return this.idKeywordField;
            }
            set {
                this.idKeywordField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DocumentoOnBaseEntity {
        
        private long idDocumentoField;
        
        private string nroSolicitudField;
        
        private string nombreDocumentoField;
        
        private string grupoDocumentoField;
        
        private string tipoDocumentoField;
        
        private string diskgroupField;
        
        private string formatoArchivoField;
        
        private string extensionArchivoField;
        
        private string usuarioAperturaField;
        
        private string usuarioNombreAperturaField;
        
        private System.DateTime fechaAperturaField;
        
        private KeywordOnBaseEntity[] keywordsField;
        
        /// <remarks/>
        public long idDocumento {
            get {
                return this.idDocumentoField;
            }
            set {
                this.idDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string nroSolicitud {
            get {
                return this.nroSolicitudField;
            }
            set {
                this.nroSolicitudField = value;
            }
        }
        
        /// <remarks/>
        public string nombreDocumento {
            get {
                return this.nombreDocumentoField;
            }
            set {
                this.nombreDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string grupoDocumento {
            get {
                return this.grupoDocumentoField;
            }
            set {
                this.grupoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string diskgroup {
            get {
                return this.diskgroupField;
            }
            set {
                this.diskgroupField = value;
            }
        }
        
        /// <remarks/>
        public string formatoArchivo {
            get {
                return this.formatoArchivoField;
            }
            set {
                this.formatoArchivoField = value;
            }
        }
        
        /// <remarks/>
        public string extensionArchivo {
            get {
                return this.extensionArchivoField;
            }
            set {
                this.extensionArchivoField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioApertura {
            get {
                return this.usuarioAperturaField;
            }
            set {
                this.usuarioAperturaField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioNombreApertura {
            get {
                return this.usuarioNombreAperturaField;
            }
            set {
                this.usuarioNombreAperturaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaApertura {
            get {
                return this.fechaAperturaField;
            }
            set {
                this.fechaAperturaField = value;
            }
        }
        
        /// <remarks/>
        public KeywordOnBaseEntity[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MensajeEntity {
        
        private string mensajeField;
        
        private MensajeTipo tipoField;
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public MensajeTipo Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MensajeTipo {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Informacion,
        
        /// <remarks/>
        Advertencia,
        
        /// <remarks/>
        Exito,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ObtenerInformacionSolicitudOnBaseCompletedEventHandler(object sender, ObtenerInformacionSolicitudOnBaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerInformacionSolicitudOnBaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerInformacionSolicitudOnBaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ImportarDocumentoCompletedEventHandler(object sender, ImportarDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportarDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportarDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void AvanzarProcesoCompletedEventHandler(object sender, AvanzarProcesoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AvanzarProcesoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AvanzarProcesoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultadoEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultadoEntity)(this.results[0]));
            }
        }
    }
}
