//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotiPerdidaTotalDuenio
    {
        public int secuencial { get; set; }
        public string nombresDuenio { get; set; }
        public string docIdDuenio { get; set; }
        public string descripcion { get; set; }
        public string idOrden { get; set; }
        public string tipoOrden { get; set; }
        public string monedaOrden { get; set; }
        public Nullable<decimal> montoOrden { get; set; }
    
        public virtual CotiPerdidaTotal CotiPerdidaTotal { get; set; }
    }
}
