//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotiReparacion
    {
        public string idItem { get; set; }
        public int idCotizacion { get; set; }
        public string chaperio { get; set; }
        public string reparacionPrevia { get; set; }
        public Nullable<bool> mecanico { get; set; }
        public string moneda { get; set; }
        public Nullable<decimal> precioCotizado { get; set; }
        public string descFijoPorcentaje { get; set; }
        public Nullable<decimal> montoDescuento { get; set; }
        public Nullable<decimal> precioFinal { get; set; }
        public string proveedor { get; set; }
    }
}
