//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotiPerdidaTotalReferencia
    {
        public int secuencial { get; set; }
        public Nullable<bool> seleccionado { get; set; }
        public string medioCotizado { get; set; }
        public string descripcion { get; set; }
        public string monedaCotizado { get; set; }
        public Nullable<decimal> montoCotizado { get; set; }
    
        public virtual CotiPerdidaTotal CotiPerdidaTotal { get; set; }
    }
}
