//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion_rc_vehicular_tercero
    {
        public int id_flujo { get; set; }
        public int id_cotizacion { get; set; }
        public long id_item { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string documento { get; set; }
        public string color { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string placa { get; set; }
        public string anio { get; set; }
        public string chasis { get; set; }
        public string taller { get; set; }
    }
}
