//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotiRCPersona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CotiRCPersona()
        {
            this.CotiRCPersonaDetalle = new HashSet<CotiRCPersonaDetalle>();
        }
    
        public int secuencial { get; set; }
        public int idCotizacion { get; set; }
        public string nombrePersona { get; set; }
        public string docIdentidadPersona { get; set; }
        public string telefonoPersona { get; set; }
        public Nullable<bool> reembolso { get; set; }
        public string idOrden { get; set; }
        public string tipoOrden { get; set; }
        public string monedaOrden { get; set; }
        public Nullable<decimal> montoOrden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotiRCPersonaDetalle> CotiRCPersonaDetalle { get; set; }
        public virtual Cotizacion Cotizacion { get; set; }
    }
}
