//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion_robo_parcial_sumatoria
    {
        public int id_flujo { get; set; }
        public int id_cotizacion { get; set; }
        public short id_tipo_item { get; set; }
        public string proveedor { get; set; }
        public Nullable<double> monto_orden { get; set; }
        public string id_tipo_descuento_orden { get; set; }
        public Nullable<double> descuento_proveedor { get; set; }
        public Nullable<double> deducible { get; set; }
        public Nullable<double> monto_final { get; set; }
        public string numero_orden { get; set; }
        public Nullable<short> id_estado { get; set; }
        public string moneda_orden { get; set; }
        public string cotizacion_proveedor { get; set; }
    }
}
