//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion_perdida_total_robo
    {
        public int id_flujo { get; set; }
        public int id_cotizacion { get; set; }
        public long id_item { get; set; }
        public Nullable<bool> condiciones_especiales { get; set; }
        public string version { get; set; }
        public string serie { get; set; }
        public string caja { get; set; }
        public string combustible { get; set; }
        public string cilindrada { get; set; }
        public Nullable<bool> techo_solar { get; set; }
        public Nullable<bool> asientos_cuero { get; set; }
        public Nullable<bool> aros_magnesio { get; set; }
        public string observaciones_vehiculo { get; set; }
        public Nullable<bool> completamente_pagado { get; set; }
        public string duenio_nombres_1 { get; set; }
        public string duenio_documento_1 { get; set; }
        public Nullable<double> duenio_monto_1 { get; set; }
        public string duenio_descripcion_1 { get; set; }
        public string duenio_nombres_2 { get; set; }
        public string duenio_documento_2 { get; set; }
        public Nullable<double> duenio_monto_2 { get; set; }
        public string duenio_descripcion_2 { get; set; }
        public string duenio_nombres_3 { get; set; }
        public string duenio_documento_3 { get; set; }
        public Nullable<double> duenio_monto_3 { get; set; }
        public string duenio_descripcion_3 { get; set; }
        public string duenio_nombres_4 { get; set; }
        public string duenio_documento_4 { get; set; }
        public Nullable<double> duenio_monto_4 { get; set; }
        public string duenio_descripcion_4 { get; set; }
        public string duenio_nombres_5 { get; set; }
        public string duenio_documento_5 { get; set; }
        public Nullable<double> duenio_monto_5 { get; set; }
        public string duenio_descripcion_5 { get; set; }
        public Nullable<bool> referencia_usada_1 { get; set; }
        public string referencia_medios_1 { get; set; }
        public string referencia_descripcion_1 { get; set; }
        public Nullable<double> referencia_monto_1 { get; set; }
        public Nullable<bool> referencia_usada_2 { get; set; }
        public string referencia_medios_2 { get; set; }
        public string referencia_descripcion_2 { get; set; }
        public Nullable<double> referencia_monto_2 { get; set; }
        public Nullable<bool> referencia_usada_3 { get; set; }
        public string referencia_medios_3 { get; set; }
        public string referencia_descripcion_3 { get; set; }
        public Nullable<double> referencia_monto_3 { get; set; }
        public Nullable<bool> referencia_usada_4 { get; set; }
        public string referencia_medios_4 { get; set; }
        public string referencia_descripcion_4 { get; set; }
        public Nullable<double> referencia_monto_4 { get; set; }
        public Nullable<bool> referencia_usada_5 { get; set; }
        public string referencia_medios_5 { get; set; }
        public string referencia_descripcion_5 { get; set; }
        public Nullable<double> referencia_monto_5 { get; set; }
        public Nullable<bool> referencia_usada_6 { get; set; }
        public string referencia_medios_6 { get; set; }
        public string referencia_descripcion_6 { get; set; }
        public Nullable<double> referencia_monto_6 { get; set; }
    }
}
