//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoSesion
    {
        public int secuencial { get; set; }
        public int idUsuario { get; set; }
        public Nullable<System.DateTime> fechaAcceso { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fechaHoraInicio { get; set; }
        public Nullable<System.DateTime> fechaHoraFin { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
