//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flujo
    {
        public int idFlujo { get; set; }
        public string flujoOnBase { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> numeroReclamo { get; set; }
        public string numeroPoliza { get; set; }
        public string marcaVehiculo { get; set; }
        public string modeloVehiculo { get; set; }
        public Nullable<int> anioVehiculo { get; set; }
        public string colorVehiculo { get; set; }
        public string placaVehiculo { get; set; }
        public string chasisVehiculo { get; set; }
        public Nullable<decimal> valorAsegurado { get; set; }
        public Nullable<bool> importacionDirecta { get; set; }
        public string nombreAsegurado { get; set; }
        public string docIdAsegurado { get; set; }
        public string telefonocelAsegurado { get; set; }
        public string causaSiniestro { get; set; }
        public Nullable<int> contador { get; set; }
        public string descripcionSiniestro { get; set; }
        public string direccionInspeccion { get; set; }
        public string agenciaAtencion { get; set; }
    }
}
