//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspRCPersona
    {
        public int secuencial { get; set; }
        public int idInspeccion { get; set; }
        public string nombrePersona { get; set; }
        public string docIdentidadPersona { get; set; }
        public string telefonoPersona { get; set; }
        public string observacionesPersona { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
