//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int idInspeccion { get; set; }
        public int idFlujo { get; set; }
        public int idUsuario { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string sucursalAtencion { get; set; }
        public string direccion { get; set; }
        public string zona { get; set; }
        public string causaSiniestro { get; set; }
        public string descripcionSiniestro { get; set; }
        public string observacionesSiniestro { get; set; }
        public string idInspector { get; set; }
        public string nombreContacto { get; set; }
        public string telefonoContacto { get; set; }
        public string correosDeEnvio { get; set; }
        public Nullable<bool> recomendacionPerdidaTotal { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha_siniestro { get; set; }
        public int tipoCobertura { get; set; }
        public int correlativo { get; set; }
        public string tipoTaller { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
