//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspRCVehicular
    {
        public int secuencial { get; set; }
        public int idInspeccion { get; set; }
        public string nombreTercero { get; set; }
        public string docIdentidadTercero { get; set; }
        public string telefonoTercero { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> anio { get; set; }
        public string placa { get; set; }
        public string color { get; set; }
        public string chasis { get; set; }
        public Nullable<int> kilometraje { get; set; }
        public Nullable<bool> importacionDirecta { get; set; }
        public string tipoTaller { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
