//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspPerdidaTotalDanios
    {
        public int idInspeccion { get; set; }
        public string version { get; set; }
        public string serie { get; set; }
        public string caja { get; set; }
        public string combustible { get; set; }
        public Nullable<int> cilindrada { get; set; }
        public Nullable<bool> techoSolar { get; set; }
        public Nullable<bool> asientosCuero { get; set; }
        public Nullable<bool> arosMagnesio { get; set; }
        public Nullable<bool> convertidoGNV { get; set; }
        public string observaciones { get; set; }
    }
}
