//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspRCObjeto
    {
        public int secuencial { get; set; }
        public int idInspeccion { get; set; }
        public string nombreObjeto { get; set; }
        public string docIdentidadObjeto { get; set; }
        public string telefonoObjeto { get; set; }
        public string observacionesObjeto { get; set; }
    }
}
