//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTaller
    {
        public string idItem { get; set; }
        public string ciudad { get; set; }
        public string taller { get; set; }
        public string categoria { get; set; }
        public string gradoReparacion { get; set; }
        public Nullable<int> secuencial { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string moneda { get; set; }
    }
}
