//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liquidacion()
        {
            this.LiquidacionDetalle = new HashSet<LiquidacionDetalle>();
            this.LiquidacionFacturas = new HashSet<LiquidacionFacturas>();
        }
    
        public int idLiquidacion { get; set; }
        public int idFlujo { get; set; }
        public int idAsegurado { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> idCotizacion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Asegurado Asegurado { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidacionDetalle> LiquidacionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidacionFacturas> LiquidacionFacturas { get; set; }
    }
}
