//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class liquidacion001_factura
    {
        public int id_flujo { get; set; }
        public long id_factura { get; set; }
        public Nullable<long> numero_factura { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<short> id_moneda { get; set; }
        public Nullable<double> monto { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> asociada { get; set; }
        public Nullable<double> tipo_cambio { get; set; }
    }
}
