//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidacionFacturas
    {
        public int secuencial { get; set; }
        public int idLiquidacion { get; set; }
        public string idOrden { get; set; }
        public Nullable<decimal> precioLiquidadoBs { get; set; }
        public Nullable<decimal> precioLiquidadoUs { get; set; }
        public Nullable<long> numeroFactura { get; set; }
        public Nullable<System.DateTime> fechaRecepcionFactura { get; set; }
        public Nullable<System.DateTime> fechaLiquidacion { get; set; }
        public string observaciones { get; set; }
    
        public virtual Liquidacion Liquidacion { get; set; }
    }
}
