//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidacionDetalle
    {
        public int secuencial { get; set; }
        public int idLiquidacion { get; set; }
        public string idOrden { get; set; }
        public string idItem { get; set; }
        public Nullable<decimal> precioCotizadoBs { get; set; }
        public Nullable<decimal> precioCotizadoUs { get; set; }
        public Nullable<System.DateTime> fechaRecepcionInspector { get; set; }
        public Nullable<bool> inspeccionado { get; set; }
        public Nullable<bool> liquidado { get; set; }
        public Nullable<long> facturaLiquidacion { get; set; }
    
        public virtual Liquidacion Liquidacion { get; set; }
    }
}
