//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPOLIQ
    {
        public int id_flujo { get; set; }
        public int id_cotizacion { get; set; }
        public short tipo_origen { get; set; }
        public long id_item { get; set; }
        public Nullable<int> existe { get; set; }
    }
}
