//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioFirma
    {
        public int idUsuario { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuarioCreacion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public byte[] firmaSello { get; set; }
    }
}
