//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICRL.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WLIQ
    {
        public int id_flujo { get; set; }
        public int id_cotizacion { get; set; }
        public short tipo_origen { get; set; }
        public long id_item { get; set; }
        public Nullable<short> id_tipo_item { get; set; }
        public string numero_orden { get; set; }
        public Nullable<System.DateTime> fecha_orden { get; set; }
        public string proveedor { get; set; }
        public string item_descripcion { get; set; }
        public Nullable<double> preciobs { get; set; }
        public Nullable<double> precious { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<bool> inspeccion { get; set; }
        public Nullable<bool> liquidacion { get; set; }
        public string num_factura { get; set; }
        public Nullable<short> id_estado { get; set; }
        public Nullable<System.DateTime> fecha_liquidacion { get; set; }
    }
}
